name = "foundr"
compatibility_date = "2025-01-01"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "foundr-db"
database_id = "your-database-id"

[[r2_buckets]]
binding = "ASSETS"
bucket_name = "foundr-assets"

[vars]
VIBESDK_URL = "https://vibesdk-production1.gogs1998.workers.dev"
VIBESDK_API_KEY = "your-vibesdk-key"

[[kv_namespaces]]
binding = "CACHE"
id = "your-kv-id"
